import "./globals.css";
import Navbar from "./component/navbar";
import Footer from "./component/footer";
import { AppWrapper } from "@/app/contextApi/Accoutsmm";
import { Toaster } from "react-hot-toast";
import {Montserrat} from "@next/font/google"
import LogOut from "./component/logout";

const Mont = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="cryptomus" content="0c446a0e" />
      </head>
      <body className={`${Mont.className} antialiased`}>
        <AppWrapper>
          <Navbar />
          <Toaster />
          <LogOut />
          {children}
          <Footer />
        </AppWrapper>
      </body>
    </html>
  );
}
